name: Blox CI
on:
  push:
    branches: [ main ]
jobs:
  publish-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - run: npm run build -w=packages/core
    - name: Publishing all packages to npm
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm config set scope "@blox"
        npm config list
        cat /home/runner/work/_temp/.npmrc
        npm publish --access public -w=packages/core -w=packages/scripts -w=packages/create-blox-app
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm run build:docs
    # copy to pages
