name: Blox Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Publish version"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
    - name: publishing
      run: |
        git config --global user.name "Blox CI"
        git config --global user.email "sharonamr@users.noreply.github.com"
        echo "version: $VERSION"
        npm version $VERSION -w=packages/core -w=packages/scripts -w=packages/create-blox-app 
        git add . && git commit -m "[skip ci] Releasing $VERSION version"
        git push origin main
      env:
        VERSION: ${{ inputs.version }}
        ACTOR: ${{ github.triggering_actor }}
    - run: npm run build -w=packages/core -w=packages/create-blox-app
    - run: npm publish --access public -w=packages/core -w=packages/scripts -w=packages/create-blox-app

    # - name: Publishing all packages to npm
    #   run: npm publish --access public -w=packages/core -w=packages/scripts -w=packages/create-blox-app
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - run: npm run build:docs
    # copy to pages